services:
  - type: web
    name: roomiematch-api
    runtime: docker
    plan: free
    region: singapore
    repo: https://github.com/hackerviet-dev/Rommie-match-project
    branch: Bao-Branch
    dockerfilePath: ./backend/src/RoomieMatch.Bootstrapper/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    buildFilter:
      paths:
        - backend/**
        - database/init/**
        - database/migrations/**
        - render.yaml
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: "8080"
      - key: Database__MigrateOnStartup
        value: "true"
      - key: ConnectionStrings__Postgres
        sync: false
      - key: Jwt__Secret
        generateValue: true
      - key: Cors__AllowedOrigins__0
        value: https://rommie-match.vercel.app
      - key: Cors__AllowedOrigins__1
        value: https://rommie-match-git-bao-branch-bingamer015-4219s-projects.vercel.app
      - key: ReverseProxy__TrustForwardedHeaders
        value: "true"
      - key: Billing__ReturnUrl
        value: https://rommie-match.vercel.app/premium/result
      - key: Billing__PublicApiBaseUrl
        value: https://roomiematch-api.onrender.com
      - key: Billing__Provider
        value: ""
