import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
process.chdir(fileURLToPath(new URL('../', import.meta.url)));
await mkdir('tmp/auth', { recursive: true });
const require = createRequire(process.cwd() + '/frontend/web-app/rommie-match/package.json');
const esbuild = require('esbuild');
await esbuild.build({entryPoints:['frontend/web-app/rommie-match/src/features/auth/index.ts'],bundle:true,platform:'node',format:'cjs',outfile:'tmp/auth/auth.cjs',define:{'import.meta.env':JSON.stringify({VITE_API_BASE_URL:'http://localhost:5000',VITE_API_URL:'http://localhost:5000'})}});
const values = new Map();
// The app stores tokens in sessionStorage; clear() also sweeps the older localStorage keys and
// fires an event on window, so all three globals must exist in Node.
const sessionValues = new Map();
globalThis.sessionStorage = {getItem:k=>sessionValues.get(k)??null,setItem:(k,v)=>sessionValues.set(k,v),removeItem:k=>sessionValues.delete(k)};
globalThis.localStorage = {getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};
globalThis.window = new EventTarget();
const {authApi,useAuthStore}=require(process.cwd()+'/tmp/auth/auth.cjs');
const email=`auth-smoke-${Date.now()}@example.com`;
const request={email,password:'RoomieTest123!',displayName:'Auth Smoke',city:'TP.HCM',gender:'male'};
const session=await authApi.register(request);
assert.notEqual(session.user.id,'me'); useAuthStore.getState().login(session);
assert.equal((await authApi.me()).email,email);
await assert.rejects(()=>authApi.login({email,password:'incorrect'}),e=>e.status===401);
const loggedIn=await authApi.login(request); useAuthStore.getState().login(loggedIn);
localStorage.setItem('roomiematch-access-token','legacy-token');
sessionStorage.setItem('roomiematch-access-token','expired-token');
const [one,two]=await Promise.all([authApi.me(),authApi.me()]);
assert.equal(one.id,two.id); assert.notEqual(sessionStorage.getItem('roomiematch-refresh-token'),loggedIn.refreshToken);
const token=sessionStorage.getItem('roomiematch-refresh-token');
await authApi.logout(token); useAuthStore.getState().logout();
assert.equal(sessionStorage.getItem('roomiematch-access-token'),null);
assert.equal(localStorage.getItem('roomiematch-access-token'),null);
await assert.rejects(()=>authApi.refresh(token),e=>e.status===401);
useAuthStore.getState().login(await authApi.login(request));
const other=await authApi.login(request);
await authApi.logoutAll(); useAuthStore.getState().logout();
await assert.rejects(()=>authApi.refresh(other.refreshToken),e=>e.status===401);
console.log('PASS: real API register, invalid password, login, me, concurrent refresh, logout, logout-all');
